
-- ###############################################################
-- HDRULES_SEED_PKG - Test amaçlı veri üretimi (Bulk)
-- NOT: İş kuralı mantığı veritabanında yoktur. Bu paket sadece test verisi üretir.
-- ###############################################################
CREATE OR REPLACE PACKAGE HDRULES_SEED_PKG AS
  PROCEDURE SEED_GROUP(p_group_code VARCHAR2, p_rule_count NUMBER DEFAULT 1000);
  PROCEDURE SEED_BULK(p_group_count NUMBER DEFAULT 5, p_rules_per_group NUMBER DEFAULT 20000);
END HDRULES_SEED_PKG;
/
CREATE OR REPLACE PACKAGE BODY HDRULES_SEED_PKG AS
  PROCEDURE SEED_GROUP(p_group_code VARCHAR2, p_rule_count NUMBER DEFAULT 1000) IS
    v_group_id HDRULES_RULE_GROUP.RULE_GROUP_ID%TYPE;
  BEGIN
    SELECT RULE_GROUP_ID INTO v_group_id FROM HDRULES_RULE_GROUP WHERE GROUP_CODE=p_group_code;
    FOR i IN 1..p_rule_count LOOP
      INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
      VALUES (v_group_id, 'BULK_'||i, 'Bulk rule '||i, MOD(i,100), 1, 1, SYSDATE);
      -- simple condition
      INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
      VALUES (HDRULES_SEQ_RULE_ID.CURRVAL, 1, 'ARAC_MODEL_YIL', 'GE', 'SCALAR', TO_CHAR(1990 + MOD(i,30)));
      INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT) VALUES (HDRULES_SEQ_RULE_ID.CURRVAL, 1, 1);
      INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
      SELECT HDRULES_SEQ_OUTPUT_ROW_ID.CURRVAL, oc.OUTPUT_COL_ID, 'CONST', TO_CHAR(100000 + MOD(i,50000))
      FROM HDRULES_OUTPUT_COL_DEF oc WHERE oc.RULE_GROUP_ID=v_group_id AND oc.COL_CODE='ARAC_BEDEL';
    END LOOP;
    COMMIT;
  END;
  PROCEDURE SEED_BULK(p_group_count NUMBER DEFAULT 5, p_rules_per_group NUMBER DEFAULT 20000) IS
    v_code VARCHAR2(50);
  BEGIN
    FOR g IN 1..p_group_count LOOP
      v_code := 'BULK_G' || g;
      INSERT INTO HDRULES_RULE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, VERSION_NO, IS_ACTIVE, VALID_FROM, CACHE_STRATEGY, CACHE_TTL_SEC)
      VALUES (v_code, 'Bulk Group '||g, 'Load test group', 1, 1, SYSDATE, 'MEMORY', 600);
      INSERT INTO HDRULES_OUTPUT_COL_DEF (RULE_GROUP_ID, COL_CODE, DISPLAY_NAME, DATA_TYPE)
      SELECT RULE_GROUP_ID, 'ARAC_BEDEL', 'Araç Bedel', 'NUMBER' FROM HDRULES_RULE_GROUP WHERE GROUP_CODE=v_code;
      COMMIT;
      SEED_GROUP(v_code, p_rules_per_group);
    END LOOP;
  END;
END HDRULES_SEED_PKG;
/
