
-- ###############################################################
-- Sample data for HDRULES*
-- Includes 2 groups: ARAC_BILGI and IKAME_ARAC_SECIMI
-- Also includes an example NRULES and an example API def
-- ###############################################################

-- ======== Rule Group: ARAC_BILGI ==================================
INSERT INTO HDRULES_RULE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, VERSION_NO, IS_ACTIVE, VALID_FROM, CACHE_STRATEGY, CACHE_TTL_SEC)
VALUES ('ARAC_BILGI', 'Araç Bilgisi Karar Tablosu', 'Marka/Model/Plaka -> Bedel/Motor/Yakıt', 1, 1, SYSDATE, 'MEMORY', 600);

-- Input params (group-level)
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, JSON_PATH, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_MODEL_YIL', 'Araç Model Yılı', 'NUMBER', null, 'Girdi: Model Yılı', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, JSON_PATH, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_MARKA', 'Araç Markası', 'STRING', null, 'Girdi: Marka', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, JSON_PATH, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_MARKA_TIP', 'Araç Marka Tip', 'STRING', null, 'Girdi: Marka Tip', 0 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, JSON_PATH, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_PLAKA', 'Araç Plaka', 'STRING', null, 'Girdi: Plaka', 0 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
-- JSON Model param examples
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, JSON_PATH, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'POLICE_ID', 'Poliçe Id', 'NUMBER', '$.Data.POLICE_ANA_BILGILER.POLICE_ID', 'JSON içinden', 0 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';

-- Output columns
INSERT INTO HDRULES_OUTPUT_COL_DEF (RULE_GROUP_ID, COL_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_BEDEL', 'Araç Bedel', 'NUMBER', 'Çıktı: Araç Bedeli', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
INSERT INTO HDRULES_OUTPUT_COL_DEF (RULE_GROUP_ID, COL_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION)
SELECT RULE_GROUP_ID, 'ARAC_MOTOR_HACIM', 'Motor Hacmi', 'NUMBER', 'Çıktı: Motor Hacmi' FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';
INSERT INTO HDRULES_OUTPUT_COL_DEF (RULE_GROUP_ID, COL_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION)
SELECT RULE_GROUP_ID, 'ARAC_YAKIT_TIP', 'Yakıt Tipi', 'STRING', 'Çıktı: Yakıt Tipi' FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';

-- Output column attributes (e.g., currency)
INSERT INTO HDRULES_OUTPUT_COL_ATTR_DEF (OUTPUT_COL_ID, ATTR_CODE, ATTR_VALUE)
SELECT oc.OUTPUT_COL_ID, 'PARA_BIRIM_KOD', 'TRY'
FROM HDRULES_OUTPUT_COL_DEF oc JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=oc.RULE_GROUP_ID
WHERE g.GROUP_CODE='ARAC_BILGI' AND oc.COL_CODE='ARAC_BEDEL';

-- Rules (a few examples)
INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'R1', '2000-2010, Mercedes|BMW|FIAT, tip=* , plaka 34M%', 100, 1, 1, SYSDATE
FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';

INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'R2', '>=2018, Marka=TOYOTA, tip=COROLLA', 90, 1, 1, SYSDATE
FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';

INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'R3', 'Her şey serbest (default)', 0, 1, 1, SYSDATE
FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='ARAC_BILGI';

-- R1 Conditions
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT, VALUE_TO_TEXT)
SELECT r.RULE_ID, 1, 'ARAC_MODEL_YIL', 'BETWEEN', 'RANGE', '2000', '2010' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R1';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 2, 'ARAC_MARKA', 'IN', 'SET', null FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R1';
INSERT INTO HDRULES_COND_SET_VALUE (CONDITION_ID, VALUE_TEXT)
SELECT c.CONDITION_ID, 'MERCEDES' FROM HDRULES_CONDITION c JOIN HDRULES_RULE r ON r.RULE_ID=c.RULE_ID WHERE r.RULE_CODE='R1' AND c.ORDINAL=2;
INSERT INTO HDRULES_COND_SET_VALUE (CONDITION_ID, VALUE_TEXT)
SELECT c.CONDITION_ID, 'BMW' FROM HDRULES_CONDITION c JOIN HDRULES_RULE r ON r.RULE_ID=c.RULE_ID WHERE r.RULE_CODE='R1' AND c.ORDINAL=2;
INSERT INTO HDRULES_COND_SET_VALUE (CONDITION_ID, VALUE_TEXT)
SELECT c.CONDITION_ID, 'FIAT' FROM HDRULES_CONDITION c JOIN HDRULES_RULE r ON r.RULE_ID=c.RULE_ID WHERE r.RULE_CODE='R1' AND c.ORDINAL=2;
-- tip = * wildcard
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 3, 'ARAC_MARKA_TIP', 'EQ', 'WILDCARD', '*' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R1';
-- plaka like '34M%'
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, LEFT_TRANSFORMS, OPERATOR, VALUE_TYPE, VALUE_TEXT, CASE_SENSITIVE)
SELECT r.RULE_ID, 4, 'ARAC_PLAKA', 'UPPER', 'LIKE', 'SCALAR', '34M%', 0 FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R1';

-- R1 Outputs (two rows, default row=1)
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='R1';
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 2, 0 FROM HDRULES_RULE r WHERE r.RULE_CODE='R1';

-- Row1 cells
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '450000'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_BEDEL'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=1;

INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '1998'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_MOTOR_HACIM'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=1;

INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', 'BENZIN'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_YAKIT_TIP'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=1;

-- Row2 cells (alternative)
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '420000'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_BEDEL'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=2;

INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '1600'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_MOTOR_HACIM'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=2;

INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', 'DIZEL'
FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_YAKIT_TIP'
WHERE r.RULE_CODE='R1' AND orow.ROW_NO=2;

-- R2 Conditions
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 1, 'ARAC_MODEL_YIL', 'GE', 'SCALAR', '2018' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R2';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 2, 'ARAC_MARKA', 'EQ', 'SCALAR', 'TOYOTA' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R2';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 3, 'ARAC_MARKA_TIP', 'EQ', 'SCALAR', 'COROLLA' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='ARAC_BILGI' AND r.RULE_CODE='R2';

-- R2 Output (single row)
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='R2';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '520000' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_BEDEL'
WHERE r.RULE_CODE='R2' AND orow.ROW_NO=1;
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '1600' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_MOTOR_HACIM'
WHERE r.RULE_CODE='R2' AND orow.ROW_NO=1;
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', 'BENZIN' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_YAKIT_TIP'
WHERE r.RULE_CODE='R2' AND orow.ROW_NO=1;

-- R3 (default catch-all) no conditions
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='R3';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '300000' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_BEDEL'
WHERE r.RULE_CODE='R3';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '1400' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_MOTOR_HACIM'
WHERE r.RULE_CODE='R3';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', 'BENZIN' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='ARAC_YAKIT_TIP'
WHERE r.RULE_CODE='R3';

-- ======== Rule Group: IKAME_ARAC_SECIMI ============================
INSERT INTO HDRULES_RULE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, VERSION_NO, IS_ACTIVE, VALID_FROM, CACHE_STRATEGY, CACHE_TTL_SEC)
VALUES ('IKAME_ARAC_SECIMI', 'İkame Araç Seçimi', 'Kullanım tarzı/marka/model -> süre(ler)', 1, 1, SYSDATE, 'MEMORY', 600);

-- Inputs
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'KULLANIM_TARZI', 'Kullanım Tarzı', 'STRING', 'hususi/kamyonet vb.', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'ARAC_MARKA', 'Araç Markası', 'STRING', 'BMW, MERCEDES, HYUNDAI...', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';
INSERT INTO HDRULES_INPUT_PARAM_DEF (RULE_GROUP_ID, PARAM_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION, IS_REQUIRED)
SELECT RULE_GROUP_ID, 'MODEL_YILI', 'Model Yılı', 'NUMBER', '>=, between destekli', 1 FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';

-- Outputs
INSERT INTO HDRULES_OUTPUT_COL_DEF (RULE_GROUP_ID, COL_CODE, DISPLAY_NAME, DATA_TYPE, DESCRIPTION)
SELECT RULE_GROUP_ID, 'IKAME_SURELERI', 'İkame Süreleri', 'JSON', 'Örn: [5,10,15]' FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';

-- Rules
INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'IK1', 'hususi + BMW + model>2015 => [5,10,15]', 100, 1, 1, SYSDATE FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';
INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'IK2', 'kamyonet + mercedes + 2020..2025 => [20]', 90, 1, 1, SYSDATE FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';
INSERT INTO HDRULES_RULE (RULE_GROUP_ID, RULE_CODE, RULE_NAME, PRIORITY, VERSION_NO, IS_ACTIVE, VALID_FROM)
SELECT RULE_GROUP_ID, 'IK3', 'hususi + hyundai + * => [15]', 80, 1, 1, SYSDATE FROM HDRULES_RULE_GROUP WHERE GROUP_CODE='IKAME_ARAC_SECIMI';

-- Conditions IK1
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 1, 'KULLANIM_TARZI', 'EQ', 'SCALAR', 'hususi' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK1';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 2, 'ARAC_MARKA', 'EQ', 'SCALAR', 'BMW' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK1';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 3, 'MODEL_YILI', 'GT', 'SCALAR', '2015' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK1';

-- IK1 output
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='IK1';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '[5,10,15]' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='IKAME_SURELERI'
WHERE r.RULE_CODE='IK1' AND orow.ROW_NO=1;

-- Conditions IK2
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 1, 'KULLANIM_TARZI', 'EQ', 'SCALAR', 'kamyonet' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK2';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 2, 'ARAC_MARKA', 'EQ', 'SCALAR', 'mercedes' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK2';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT, VALUE_TO_TEXT, CASE_SENSITIVE)
SELECT r.RULE_ID, 3, 'MODEL_YILI', 'BETWEEN', 'RANGE', '2020', '2025', 0 FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK2';

-- IK2 output
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='IK2';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '[20]' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='IKAME_SURELERI'
WHERE r.RULE_CODE='IK2' AND orow.ROW_NO=1;

-- Conditions IK3 (wildcard year)
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 1, 'KULLANIM_TARZI', 'EQ', 'SCALAR', 'hususi' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK3';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 2, 'ARAC_MARKA', 'EQ', 'SCALAR', 'hyundai' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK3';
INSERT INTO HDRULES_CONDITION (RULE_ID, ORDINAL, LEFT_PARAM_CODE, OPERATOR, VALUE_TYPE, VALUE_TEXT)
SELECT r.RULE_ID, 3, 'MODEL_YILI', 'EQ', 'WILDCARD', '*' FROM HDRULES_RULE r JOIN HDRULES_RULE_GROUP g ON r.RULE_GROUP_ID=g.RULE_GROUP_ID WHERE g.GROUP_CODE='IKAME_ARAC_SECIMI' AND r.RULE_CODE='IK3';

-- IK3 output
INSERT INTO HDRULES_RULE_OUTPUT_ROW (RULE_ID, ROW_NO, IS_DEFAULT)
SELECT r.RULE_ID, 1, 1 FROM HDRULES_RULE r WHERE r.RULE_CODE='IK3';
INSERT INTO HDRULES_RULE_OUTPUT_CELL (OUTPUT_ROW_ID, OUTPUT_COL_ID, SOURCE_TYPE, CONST_VALUE)
SELECT orow.OUTPUT_ROW_ID, oc.OUTPUT_COL_ID, 'CONST', '[15]' FROM HDRULES_RULE_OUTPUT_ROW orow
JOIN HDRULES_RULE r ON r.RULE_ID=orow.RULE_ID
JOIN HDRULES_RULE_GROUP g ON g.RULE_GROUP_ID=r.RULE_GROUP_ID
JOIN HDRULES_OUTPUT_COL_DEF oc ON oc.RULE_GROUP_ID=g.RULE_GROUP_ID AND oc.COL_CODE='IKAME_SURELERI'
WHERE r.RULE_CODE='IK3' AND orow.ROW_NO=1;

-- ======== API DEF EXAMPLE (dummy) ===============================
INSERT INTO HDRULES_API_DEF (API_CODE, NAME, METHOD, URL, HEADERS, BODY_TEMPLATE, TIMEOUT_SEC, DESCRIPTION)
VALUES ('PLAKA_SORGU', 'Plaka Servisi', 'GET', 'https://dummy.local/api/plaka/{plaka}', '{"Authorization":"Bearer {token}"}', NULL, 5, 'Demo amaçlı');

-- ======== NRULES EXAMPLE ========================================
INSERT INTO HDRULES_NRULES_DEF (RULE_GROUP_ID, NRULES_CODE, NAME, CSHARP_CODE, IS_ACTIVE)
SELECT g.RULE_GROUP_ID, 'SUM_TEMINAT_A_B', 'Kırmızı araç -> teminat a+b', q'[
using System;
using System.Linq;
using System.Collections.Generic;
using NRules.Fluent.Dsl;
public class SumTeminatABRule : Rule
{
    public override void Define()
    {
        dynamic ctx = null;
        When()
            .Match<dynamic>(() => ctx, c => 
                (string)(c.Data?.ARAC_RENGI ?? "") == "kirmizi"
            );
        Then()
            .Do(_ => {
                // Expect input JSON-like object with Data.POLICE_TEMINATLARI as array of items with TEMINAT_KOD and BEDEL fields
                try
                {
                    var list = (IEnumerable<object>)ctx.Data.POLICE_TEMINATLARI;
                    decimal toplam = 0M;
                    foreach (dynamic t in list)
                    {
                        var kod = (string)(t.TEMINAT_KOD ?? "");
                        if (kod == "a" || kod == "b")
                        {
                            decimal bedel;
                            if (decimal.TryParse(Convert.ToString(t.BEDEL ?? "0"), out bedel))
                                toplam += bedel;
                        }
                    }
                    ctx.__NRULES_OUTPUT = new Dictionary<string, object> { { "TOPLAM_TEMINAT_AB", toplam } };
                }
                catch { ctx.__NRULES_OUTPUT = new Dictionary<string, object> { { "TOPLAM_TEMINAT_AB", 0M } }; }
            });
    }
}
]', 1
FROM HDRULES_RULE_GROUP g WHERE g.GROUP_CODE='ARAC_BILGI';
